# Generated by Django 4.2.3 on 2023-09-08 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
