FROM python

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .
#ENTRYPOINT [ "python3", "sleep.py" ]

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]